"use client";

import { useState, useCallback } from "react";
import { Project, Photo, ReportPhoto } from "@/types";
import { PhotoTagBadge } from "@/components/ui/PhotoTagBadge";
import { formatDate } from "@/lib/utils";
import { cn } from "@/lib/utils";

interface ReportPanelProps {
  project: Project;
  photos: Photo[];
}

export function ReportPanel({ project, photos }: ReportPanelProps) {
  const [selected, setSelected] = useState<ReportPhoto[]>([]);
  const [generating, setGenerating] = useState(false);
  const [preview, setPreview] = useState(false);

  const togglePhoto = (photo: Photo) => {
    setSelected((prev) => {
      const exists = prev.find((r) => r.photo.id === photo.id);
      if (exists) {
        return prev.filter((r) => r.photo.id !== photo.id);
      }
      return [
        ...prev,
        {
          photo,
          caption: photo.caption || "",
          order: prev.length + 1,
        },
      ];
    });
  };

  const updateCaption = (photoId: string, caption: string) => {
    setSelected((prev) =>
      prev.map((r) => (r.photo.id === photoId ? { ...r, caption } : r))
    );
  };

  const moveUp = (idx: number) => {
    if (idx === 0) return;
    setSelected((prev) => {
      const arr = [...prev];
      [arr[idx - 1], arr[idx]] = [arr[idx], arr[idx - 1]];
      return arr;
    });
  };

  const moveDown = (idx: number) => {
    setSelected((prev) => {
      if (idx >= prev.length - 1) return prev;
      const arr = [...prev];
      [arr[idx], arr[idx + 1]] = [arr[idx + 1], arr[idx]];
      return arr;
    });
  };

  const generatePDF = useCallback(async () => {
    if (selected.length === 0) return;
    setGenerating(true);

    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "letter" });

      const pageW = doc.internal.pageSize.getWidth();
      const pageH = doc.internal.pageSize.getHeight();
      const margin = 40;
      const contentW = pageW - margin * 2;

      // ---- Cover page ----
      // Header bar
      doc.setFillColor(27, 42, 74); // navy
      doc.rect(0, 0, pageW, 80, "F");

      // Company name
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.setFont("helvetica", "bold");
      doc.text("Roof Repair Partners", margin, 35);
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.text("RRP Field Documentation Report", margin, 55);

      // Red accent bar
      doc.setFillColor(192, 57, 43); // red
      doc.rect(0, 80, pageW, 6, "F");

      // Project info
      let y = 130;
      doc.setTextColor(27, 42, 74);
      doc.setFontSize(18);
      doc.setFont("helvetica", "bold");
      const addressLines = doc.splitTextToSize(project.address, contentW);
      doc.text(addressLines, margin, y);
      y += addressLines.length * 22 + 10;

      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(80, 80, 80);

      const infoRows = [
        ["Customer:", project.customer_name],
        ["Job Type:", project.job_type],
        ["Status:", project.status],
        ...(project.shingle_color ? [["Shingle Color:", project.shingle_color]] : []),
        ["Report Date:", formatDate(new Date().toISOString())],
        ["Created:", formatDate(project.created_at)],
        ["Photos Included:", String(selected.length)],
      ];

      infoRows.forEach(([label, value]) => {
        doc.setTextColor(120, 120, 120);
        doc.setFont("helvetica", "bold");
        doc.text(label, margin, y);
        doc.setTextColor(40, 40, 40);
        doc.setFont("helvetica", "normal");
        doc.text(value, margin + 120, y);
        y += 20;
      });

      if (project.notes) {
        y += 10;
        doc.setFont("helvetica", "bold");
        doc.setTextColor(120, 120, 120);
        doc.text("Notes:", margin, y);
        y += 18;
        doc.setFont("helvetica", "normal");
        doc.setTextColor(60, 60, 60);
        const noteLines = doc.splitTextToSize(project.notes, contentW);
        doc.text(noteLines, margin, y);
        y += noteLines.length * 16;
      }

      // Footer on cover
      doc.setFillColor(245, 245, 245);
      doc.rect(0, pageH - 40, pageW, 40, "F");
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(
        `Generated by RRP Field Docs · ${new Date().toLocaleDateString()}`,
        margin,
        pageH - 16
      );

      // ---- Photo pages ----
      const COLS = 2;
      const photoW = (contentW - 16) / COLS;
      const photoH = photoW * 0.75;
      const PHOTOS_PER_PAGE = 4;

      for (let i = 0; i < selected.length; i++) {
        const isFirst = i % PHOTOS_PER_PAGE === 0;
        if (isFirst) {
          doc.addPage();

          // Page header
          doc.setFillColor(27, 42, 74);
          doc.rect(0, 0, pageW, 40, "F");
          doc.setTextColor(255, 255, 255);
          doc.setFontSize(10);
          doc.setFont("helvetica", "bold");
          doc.text("Roof Repair Partners", margin, 18);
          doc.setFont("helvetica", "normal");
          doc.setFontSize(9);
          doc.text(project.address, margin, 32);

          // Page number
          const pageNum = Math.floor(i / PHOTOS_PER_PAGE) + 2;
          doc.text(`Page ${pageNum}`, pageW - margin - 30, 24);

          // Red line
          doc.setFillColor(192, 57, 43);
          doc.rect(0, 40, pageW, 3, "F");
        }

        const pageIdx = i % PHOTOS_PER_PAGE;
        const col = pageIdx % COLS;
        const row = Math.floor(pageIdx / COLS);

        const px = margin + col * (photoW + 16);
        const py = 60 + row * (photoH + 60);

        const { photo, caption } = selected[i];

        // Photo placeholder / image
        try {
          const imgData = await fetchImageAsBase64(photo.thumbnailUrl);
          doc.addImage(imgData, "JPEG", px, py, photoW, photoH);
        } catch {
          // Fallback box if image fails
          doc.setFillColor(240, 240, 240);
          doc.rect(px, py, photoW, photoH, "F");
          doc.setFontSize(8);
          doc.setTextColor(160, 160, 160);
          doc.text("Photo unavailable", px + photoW / 2, py + photoH / 2, { align: "center" });
        }

        // Tag badge
        if (photo.tag) {
          const tagColors: Record<string, [number, number, number]> = {
            Before: [255, 237, 213],
            After: [209, 250, 229],
            Damage: [254, 226, 226],
            "In Progress": [254, 252, 232],
            Complete: [219, 234, 254],
          };
          const tagTextColors: Record<string, [number, number, number]> = {
            Before: [194, 65, 12],
            After: [6, 95, 70],
            Damage: [153, 27, 27],
            "In Progress": [133, 77, 14],
            Complete: [29, 78, 216],
          };
          const [br, bg, bb] = tagColors[photo.tag] || [240, 240, 240];
          const [tr, tg, tb] = tagTextColors[photo.tag] || [0, 0, 0];
          doc.setFillColor(br, bg, bb);
          doc.roundedRect(px + 4, py + 4, 50, 14, 3, 3, "F");
          doc.setFontSize(7);
          doc.setFont("helvetica", "bold");
          doc.setTextColor(tr, tg, tb);
          doc.text(photo.tag, px + 29, py + 13, { align: "center" });
        }

        // Caption
        const captionText = caption || photo.name;
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(60, 60, 60);
        const captionLines = doc.splitTextToSize(captionText, photoW);
        doc.text(captionLines.slice(0, 2), px, py + photoH + 14);

        // Photo number
        doc.setFontSize(7);
        doc.setTextColor(160, 160, 160);
        doc.text(`Photo ${i + 1} of ${selected.length}`, px, py + photoH + 28);
      }

      doc.save(
        `RRP_Report_${project.address.replace(/[^a-z0-9]/gi, "_")}_${formatDate(new Date().toISOString())}.pdf`
      );
    } catch (err) {
      console.error("PDF generation error:", err);
      alert("Failed to generate PDF. Please try again.");
    } finally {
      setGenerating(false);
    }
  }, [selected, project]);

  return (
    <div className="space-y-4">
      {/* Info */}
      <div className="card p-5">
        <h3 className="section-title mb-1">Photo Report Generator</h3>
        <p className="text-sm text-gray-500">
          Select photos, add captions, arrange order, then download as PDF.
        </p>
        {selected.length > 0 && (
          <div className="mt-4 flex items-center justify-between">
            <span className="text-sm font-medium text-navy-700">
              {selected.length} photo{selected.length !== 1 ? "s" : ""} selected
            </span>
            <div className="flex gap-2">
              <button
                onClick={() => setPreview(!preview)}
                className="btn-secondary py-2 text-sm"
              >
                {preview ? "Edit" : "Preview Order"}
              </button>
              <button
                onClick={generatePDF}
                disabled={generating}
                className="btn-primary py-2 text-sm"
              >
                {generating ? (
                  <>
                    <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                    Generating PDF...
                  </>
                ) : (
                  <>
                    <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                    Download PDF
                  </>
                )}
              </button>
            </div>
          </div>
        )}
      </div>

      {photos.length === 0 ? (
        <div className="card p-10 text-center">
          <p className="text-gray-400 text-sm">Upload photos to this project first, then generate a report.</p>
        </div>
      ) : preview && selected.length > 0 ? (
        /* Preview/order mode */
        <div className="card divide-y divide-gray-50">
          <div className="px-4 py-3 flex items-center justify-between">
            <h4 className="text-sm font-semibold text-gray-700">Report Order & Captions</h4>
            <span className="text-xs text-gray-400">{selected.length} photos</span>
          </div>
          {selected.map((rp, idx) => (
            <div key={rp.photo.id} className="flex gap-3 p-4 items-start">
              <div className="flex flex-col gap-1 shrink-0">
                <button onClick={() => moveUp(idx)} disabled={idx === 0} className="w-6 h-6 rounded hover:bg-gray-100 flex items-center justify-center disabled:opacity-30">
                  <svg className="w-4 h-4 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M5 15l7-7 7 7" />
                  </svg>
                </button>
                <span className="text-xs text-gray-400 text-center font-bold">{idx + 1}</span>
                <button onClick={() => moveDown(idx)} disabled={idx === selected.length - 1} className="w-6 h-6 rounded hover:bg-gray-100 flex items-center justify-center disabled:opacity-30">
                  <svg className="w-4 h-4 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
                  </svg>
                </button>
              </div>

              {/* eslint-disable-next-line @next/next/no-img-element */}
              <div className="w-20 h-16 rounded-lg overflow-hidden bg-gray-100 shrink-0">
                {rp.photo.thumbnailUrl && (
                  <img src={rp.photo.thumbnailUrl} alt="" className="w-full h-full object-cover" />
                )}
              </div>

              <div className="flex-1 min-w-0 space-y-1.5">
                {rp.photo.tag && <PhotoTagBadge tag={rp.photo.tag} />}
                <input
                  type="text"
                  value={rp.caption}
                  onChange={(e) => updateCaption(rp.photo.id, e.target.value)}
                  placeholder="Add caption..."
                  className="w-full text-sm border border-gray-200 rounded-lg px-2.5 py-1.5 focus:outline-none focus:ring-1 focus:ring-navy-400"
                />
              </div>

              <button onClick={() => togglePhoto(rp.photo)} className="shrink-0 text-gray-300 hover:text-red-400 transition-colors">
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
          ))}
        </div>
      ) : (
        /* Selection grid */
        <div>
          <div className="flex items-center justify-between mb-3">
            <p className="text-sm text-gray-500">Select photos to include in the report:</p>
            <div className="flex gap-2">
              <button
                onClick={() => setSelected(photos.map((p, i) => ({ photo: p, caption: p.caption || "", order: i + 1 })))}
                className="text-xs text-navy-600 hover:text-navy-800 font-medium"
              >
                Select all
              </button>
              <span className="text-gray-300">·</span>
              <button onClick={() => setSelected([])} className="text-xs text-gray-400 hover:text-gray-600 font-medium">
                Clear
              </button>
            </div>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
            {photos.map((photo) => {
              const isSelected = selected.some((r) => r.photo.id === photo.id);
              const orderIdx = selected.findIndex((r) => r.photo.id === photo.id);

              return (
                <button
                  key={photo.id}
                  onClick={() => togglePhoto(photo)}
                  className={cn(
                    "relative aspect-square rounded-xl overflow-hidden bg-gray-100 border-2 transition-all",
                    isSelected
                      ? "border-navy-600 ring-2 ring-navy-300"
                      : "border-transparent hover:border-gray-300"
                  )}
                >
                  {photo.thumbnailUrl ? (
                    // eslint-disable-next-line @next/next/no-img-element
                    <img
                      src={photo.thumbnailUrl}
                      alt=""
                      className="w-full h-full object-cover"
                    />
                  ) : (
                    <div className="absolute inset-0 flex items-center justify-center bg-gray-100">
                      <svg className="w-6 h-6 text-gray-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                      </svg>
                    </div>
                  )}

                  {/* Selection indicator */}
                  {isSelected && (
                    <div className="absolute top-1.5 right-1.5 w-6 h-6 bg-navy-600 rounded-full flex items-center justify-center shadow-lg">
                      <span className="text-white text-xs font-bold">{orderIdx + 1}</span>
                    </div>
                  )}

                  {/* Tag */}
                  {photo.tag && (
                    <div className="absolute bottom-1 left-1">
                      <PhotoTagBadge tag={photo.tag} />
                    </div>
                  )}
                </button>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}

async function fetchImageAsBase64(url: string): Promise<string> {
  const res = await fetch(`/api/proxy-image?url=${encodeURIComponent(url)}`);
  if (!res.ok) throw new Error("Failed to fetch image");
  const blob = await res.blob();
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result as string);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}
